export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-001',
    idnum: '199245800123',
    name: 'Kasun Jayawardena',
    employer: 'Port Logistics Ltd',
    role: 'Forklift Operator',
    dept: 'Warehouse Operations',
  },
  {
    id: 'EMP-002',
    idnum: '198834100456',
    name: 'Nimal Perera',
    employer: 'Harbor Cranes Corp',
    role: 'Crane Operator',
    dept: 'Yard & Logistics',
  },
  {
    id: 'EMP-003',
    idnum: '199578200789',
    name: 'Sunethra Silva',
    employer: 'Safety First Subcontractors',
    role: 'Safety Inspector',
    dept: 'HSE Safety Division',
  },
  {
    id: 'EMP-004',
    idnum: '199012300999',
    name: 'Dinesh Bandara',
    employer: 'Cargo Movements Co',
    role: 'Heavy Vehicle Driver',
    dept: 'Transport & Fleet',
  },
  {
    id: 'EMP-005',
    idnum: '198555400111',
    name: 'Ruwan Fernando',
    employer: 'Port Logistics Ltd',
    role: 'Maintenance Engineer',
    dept: 'Engineering & Maintenance',
  },
];

export const INITIAL_INCIDENTS = [
  {
    id: 'INC-001',
    empId: 'EMP-001',
    date: '2026-03-15T10:30',
    type: 'Accident',
    category: 'Container',
    shift: 'Day',
    location: 'Yard Berth 4',
    equipment: 'Forklift Model X200',
    injury: 'Cut / Laceration',
    bodypart: 'Right Forearm',
    desc: 'While maneuvering container pallets in Yard Berth 4, the forklift hydraulic hose leaked fluid causing sudden loss of braking power and collision with wooden stack.',
    action: 'First aid applied immediately at site, hydraulic line isolated and maintenance team dispatched.',
    witness: 'Sarath Wickramasinghe',
    reporter: 'Safety Officer Jayasuriya',
    status: 'Under Review',
    docs: [
      {
        name: 'INC-001_Initial_Statement.pdf',
        data: 'data:application/pdf;base64,JVBERi0xLjQKJ...',
        docType: 'Statement',
        uploadedAt: '2026-03-15',
      },
    ],
  },
  {
    id: 'INC-002',
    empId: 'EMP-002',
    date: '2026-03-18T22:15',
    type: 'Near Miss',
    category: 'Ro Ro',
    shift: 'Night',
    location: 'Deck Terminal 2',
    equipment: 'Gantry Crane #3',
    injury: 'None',
    bodypart: 'N/A',
    desc: 'Crane hook wire swung unexpectedly during night shift wind gust. Container cleared vehicle cab roof by less than 20cm without impact.',
    action: 'Night operations temporarily halted for 30 minutes, anemometer wind check performed.',
    witness: 'Kamal Gunaratne',
    reporter: 'Shift Sup. Silva',
    status: 'Completed',
    docs: [],
  },
  {
    id: 'INC-003',
    empId: 'EMP-001',
    date: '2026-02-10T14:00',
    type: 'Injury',
    category: 'Fire',
    shift: 'Day',
    location: 'Workshop B',
    equipment: 'Welding Torch Unit',
    injury: 'Burn',
    bodypart: 'Left Wrist',
    desc: 'Minor flash burn while operating arc welder in Workshop B due to loose protective heat shield.',
    action: 'Cold water flush applied, topical burn ointment provided at medical station.',
    witness: 'Mahinda Kumara',
    reporter: 'Kasun Jayawardena',
    status: 'Completed',
    docs: [],
  },
  {
    id: 'INC-004',
    empId: 'EMP-004',
    date: '2026-01-22T08:45',
    type: 'Incident',
    category: 'Construction',
    shift: 'Day',
    location: 'Gate 3 Access Road',
    equipment: 'Dump Truck T-04',
    injury: 'Sprain / Strain',
    bodypart: 'Left Ankle',
    desc: 'Driver slipped off the truck side step when dismounting onto wet unpaved gravel surface.',
    action: 'Compression bandage applied, driver assigned to light administrative duties.',
    witness: 'Chamara Silva',
    reporter: 'Inspector Bandara',
    status: 'Opened',
    docs: [],
  },
];
